name: "JD Docker Image Buildx Stable Github V4"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build JD Docker Image Stable Github
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: ohmybobo/jds
          dockerFile: docker/github/Dockerfile
          platform: linux/amd64
          tag: v4
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
